<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
    </line>
    <line>
      <![CDATA[Login Page is displayed and it is verified ]]>
    </line>
    <line>
      <![CDATA[DashBoard Page is displayed and it is verified]]>
    </line>
    <line>
      <![CDATA[TestScript Excecution Skipped]]>
    </line>
    <line>
      <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
    </line>
    <line>
      <![CDATA[TestScript Excecution Skipped]]>
    </line>
    <line>
      <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
    </line>
    <line>
      <![CDATA[TestScript Excecution Skipped]]>
    </line>
    <line>
      <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
    </line>
    <line>
      <![CDATA[TestScripts Exc Failed]]>
    </line>
  </reporter-output>
  <suite started-at="2023-03-29T10:26:27 IST" name="Suite" finished-at="2023-03-29T10:26:34 IST" duration-ms="7010">
    <groups>
      <group name="integration">
        <method signature="BranchCreatedByHrHead_BaseClass.BranchCreatedByHrHead()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" name="BranchCreatedByHrHead" class="branchModule.BranchCreatedByHrHead_BaseClass"/>
      </group> <!-- integration -->
    </groups>
    <test started-at="2023-03-29T10:26:27 IST" name="Test" finished-at="2023-03-29T10:26:34 IST" duration-ms="7010">
      <class name="branchModule.BranchCreatedByHrHead_BaseClass">
        <test-method is-config="true" signature="configBS()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:26 IST" name="configBS" finished-at="2023-03-29T10:26:26 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:27 IST" name="configBC" finished-at="2023-03-29T10:26:30 IST" duration-ms="2919" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method retried="true" signature="BranchCreatedByHrHead()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:30 IST" name="BranchCreatedByHrHead" finished-at="2023-03-29T10:26:32 IST" duration-ms="2002" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at branchModule.BranchCreatedByHrHead_BaseClass.BranchCreatedByHrHead(BranchCreatedByHrHead_BaseClass.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
            </line>
            <line>
              <![CDATA[Login Page is displayed and it is verified ]]>
            </line>
            <line>
              <![CDATA[DashBoard Page is displayed and it is verified]]>
            </line>
            <line>
              <![CDATA[TestScript Excecution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- BranchCreatedByHrHead -->
        <test-method retried="true" signature="BranchCreatedByHrHead()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:32 IST" name="BranchCreatedByHrHead" finished-at="2023-03-29T10:26:32 IST" duration-ms="120" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is not displayed and it is verified  expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is not displayed and it is verified  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at branchModule.BranchCreatedByHrHead_BaseClass.BranchCreatedByHrHead(BranchCreatedByHrHead_BaseClass.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
            </line>
            <line>
              <![CDATA[TestScript Excecution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- BranchCreatedByHrHead -->
        <test-method retried="true" signature="BranchCreatedByHrHead()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:32 IST" name="BranchCreatedByHrHead" finished-at="2023-03-29T10:26:32 IST" duration-ms="82" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is not displayed and it is verified  expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is not displayed and it is verified  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at branchModule.BranchCreatedByHrHead_BaseClass.BranchCreatedByHrHead(BranchCreatedByHrHead_BaseClass.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
            </line>
            <line>
              <![CDATA[TestScript Excecution Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- BranchCreatedByHrHead -->
        <test-method signature="BranchCreatedByHrHead()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:32 IST" name="BranchCreatedByHrHead" finished-at="2023-03-29T10:26:32 IST" duration-ms="141" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page is not displayed and it is verified  expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page is not displayed and it is verified  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at branchModule.BranchCreatedByHrHead_BaseClass.BranchCreatedByHrHead(BranchCreatedByHrHead_BaseClass.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[BranchCreatedByHrHead---> TestScript excecution started]]>
            </line>
            <line>
              <![CDATA[TestScripts Exc Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- BranchCreatedByHrHead -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:32 IST" name="configAC" finished-at="2023-03-29T10:26:34 IST" duration-ms="1189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:branchModule.BranchCreatedByHrHead_BaseClass@47987356]" started-at="2023-03-29T10:26:34 IST" name="configAS" finished-at="2023-03-29T10:26:34 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- branchModule.BranchCreatedByHrHead_BaseClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
